### ISSUE TITLE
What a versatile logging library! 

### ISSUE THREAD

**Issue by edwinyzh** [exilon/QuickLogger#1]
But unfortunately it doesn't compile under XE4...

**Comment by exilon** [comment]
Please, can you explain where fails to compile?

**Comment by edwinyzh** [comment]
Sorry for my late reply, I somehow missed the email notification of this issue. It's the QuickLib that's failed to compile:

> [dcc32 Error] Quick.Commons.pas(56): E2001 Ordinal type required
> [dcc32 Error] Quick.Commons.pas(56): E2010 Incompatible types: 'Integer' and 'string'
> [dcc32 Error] Quick.Commons.pas(56): E2010 Incompatible types: 'Integer' and 'string'
> [dcc32 Fatal Error] Quick.Console.pas(53): F2063 Could not compile used unit 'Quick.Commons.pas'

**Comment by exilon** [comment]
QuickLib and QuickLogger are XE4 compatibles now. Please check it.

**Comment by edwinyzh** [comment]
Great! Thanks, now it compiles, except one place:
```
constructor TSMTP.Create;
begin
  inherited Create;
  ...
end;
```
I don't know why, but with my xe4 compiler `inherited;` has to be changed to `inherited Create;'.

**Comment by exilon** [comment]
Ok, I changed it.
