### ISSUE TITLE
ElasticSearchProvider : 400 Bad Request

### ISSUE THREAD

**Issue by SimonCtl** [exilon/QuickLogger#101]
Hi,

Trying to send logs to ELK but always getting HTTP 400 Bad Request.
![erreur](https://github.com/exilon/QuickLogger/assets/74704575/e2cbb202-3838-4e63-8825-dc4dd5a52a18)

Here is my conf : 
![config](https://github.com/exilon/QuickLogger/assets/74704575/3d3c38e8-b497-4807-a18b-44741876864e)

I tried the sample project available on Github, same error.
ELK is working, I do have another .NET project pushing logs directly to this same ELK.

Thanks in advance!

**Comment by exilon** [comment]
In newer elastic versions you should change: ` DocType := "_doc"`

**Comment by SimonCtl** [comment]
Working with sample project. Thanks !
