### ISSUE TITLE
[dcc32 Error] Quick.Json.Serializer.pas(516): E2003 Undeclared identifier: 'rfield'

### ISSUE THREAD

**Issue by Rik69** [exilon/QuickLogger#12]
I just download the latest version.  I get this error from Delphi Tokyo when I try to use QuickLogger (latest version also).

[dcc32 Error] Quick.Json.Serializer.pas(516): E2003 Undeclared identifier: 'rfield'

**Comment by exilon** [comment]
Solved. Please download last Quick.Lib commit.
