### ISSUE TITLE
FileLogger doesn't handle concurrency

### ISSUE THREAD

**Issue by luebbe** [exilon/QuickLogger#2]
Just start the demo twice. The second instance will crash.
You should either use a unique file name (GUID or ProcessID) during logging to avoid collisions or you have to invent some clever mechanism to avoid two instances to log into the same file. I'd recommend one file per instance/per run. Keep the last 10-20 logs (configurable) 
After logging is done, you can rename the log files from the different instances to your liking. Use a mutex or whatever to prevent name collisions while doing so.

**Comment by exilon** [comment]
Filelogger provider is working fine with concurrency (multithread applications). You're talking about multi instance/process access.
IMHO it's not a good practise to have two or more processes writing to the same log file. You can configure every process with a separate filename with no problem (if you don't define a custom filename, filelogger will use "appname" + log by default)

**Comment by luebbe** [comment]
Yes, I'm talking about multi instance access. The default "appname" + log is exactly the reason why it doesn't work. OK, I can make the filename unique myself, but IMHO the logging framework should (optionally) be able to handle this on its own.

**Comment by exilon** [comment]
I've added optional Autocreation by processId
You need to set GlobalLogFileProvider.AutoFileNameByProcess := True before Enable FileLogger provider
and your filename will be filename + _ + processId + .log

**Comment by luebbe** [comment]
Great, thanks!
