### ISSUE TITLE
Question.  Process and Thread Id.

### ISSUE THREAD

**Issue by epachsoft** [exilon/QuickLogger#21]
Hi there,

Fantastic job with your Logger.  I'm trying to push your work around the community, very well done.

I have a question, I'm certain that you had lots of experience with existing loggers so I'm wondering why did you left out the current thread and process id from the default per line output.

These are essential on service/backend/multithreaded applications.  We could add CurrentThread.ThreadId, etc on every output but it seems to be one of those basic things that should be included, what do you think?

Thank you in advance and thank you for your work.

**Comment by exilon** [comment]
There are many things can be included on every output. Many of them are supported by default, but you can add your own info setting the CustomOutput property (see repository documentation).
I've included ThreadId and PID (only for Windows at this moment) as an optional IncludedInfo in last release 1.42. Please try it (you will need to pull QuickLib and QuickLogger repositories)

**Comment by epachsoft** [comment]
Hi,
I quickly tested the new additions and seemed to be working.  I searched for the CustomOutput property on quicklib and QuickLogger and couldnt find it.  Maybe, and most probably, Im missing something :).

It all seems to be good, thank you for your work, I'll be introducing your logger to several services to see its interaction via forwarders with Splunk (yeah, yeah, not open source :( ).  Which seems to prefer all indexable data with "=", Ill later compare it with the direct upload to Elastic.

Once again great job.
