### ISSUE TITLE
in Linux console application

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLogger#24]
i used in CentOS 7.x with QuickLogger. (Thank you very much~ it's so much useful library~)
- (Delphi 10.3.2, QuickLogger and QuickLib from GetIt Manager - 1.8 i think..)

Logger's writing in file normally in nomal process.
but after fork not working.

i used like this.

var
  vPid : pid_t;

begin
    vPid                      := fork;
    if vPid > 0 then
    begin
       // Parent
      Exit;
    end
    else if vPid = 0 then
    begin
      // Fork process
    end
    else if vPid = -1 then
    begin
      // fork Error
      Writeln('Fork error [' + errno.ToString + ']');
      Exit;
    end;

    Logger.Providers.Add(GlobalLogFileProvider);
    with GlobalLogFileProvider do
    begin
      DailyRotate                 := True;
      LogLevel                    := LOG_DEBUG;
      Enabled                     := True;
      TimePrecission              := True;
    end;

    Logger.Providers.Add(GlobalLogConsoleProvider);
    with GlobalLogConsoleProvider do
    begin
      LogLevel                    := LOG_ALL;
      ShowEventColors             := True;
      ShowTimeStamp               := True;
      TimePrecission              := True;
      Enabled                     := True;
    end;

    Logger.Info('log Execute');
    Logger.Trace('log Execute');
    Logger.Error('log Execute');

Logger.info, Trace, Error --> Not Working.

**Comment by exilon** [comment]
Hi SamJokO,
I think problem was with file provider. When you fork a process, you clone all but with different PID, but new process uses same file. In Windows, if you want to log different process you need to set GlobalLogFileProvider.AutoFileNameByProcess := True before Enable FileLogger provider
and your filename will be filename + _ + processId + .log. Not irmplemented in Linux, but please confirm if this is your problem a i will try to implement it.

**Comment by SamJokO** [comment]
Hi, exilon.
Thank u for your suggestion.
But, that's not the point. (I think...)
i try fork after GlobalFileLogger. not sharing file pointer. (i did fork after halt(1))
i test some log into TLogFileProvider.WriteLog.
used tstringlist and finally savetofile.
but, it's not working.
i think thread is suspended or not execute. 
it's so weired.

**Comment by SamJokO** [comment]
Hi, exilon.

Logger created in Quick.Logger "initialization" section.
it means program launching after first allocation Logger instance.
but. linux fork is only one thread(main-thread) copy.
fork is not safety in multithread.
i try  logger.free after fork --> first exception (because. memory copy success, but thread not working. it means possible memory leak in library)
btw, after exception create new instance.
Logger := TLogger.Create;  <-- like this.
it's successfully working well.
i think fork and initialization's combination problem.

Thank you. 

p.s : sorry for my poor english.
