### ISSUE TITLE
Logger with console (log type)

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLogger#25]
Hello, exilon~

1298 line in Quick.Logger 

procedure TLogger.Trace(const cMsg: string);
begin
  Self.Add(cMsg,TEventType.etDebug);
end;

it's should be etTract.. isn't it?

and, in log text in linux console with color.
it's not working just except first line.
first line is showing color is well done.
but, second line with color text include like this.
;97m20-11-2019 08:46:28.994 [INFO] Blah, Blah...

I'll try change TextBackground procedure in Quick.Console
{$IF DEFINED(DELPHILINUX) OR DEFINED(MACOS)}
    write(AEC,0,';',Color+10*10);
{$ELSE}
-->
{$IF DEFINED(DELPHILINUX) OR DEFINED(MACOS)}
    write(AEC,0,'m');
{$ELSE}

it's working well. but, i think this is not correct way~.
 
Thank you anyway~.

**Comment by exilon** [comment]
Thanks for your report.
I've fixed these mistakes. Please get last updates from QuickLib and QuickLogger to resolve these issues.

**Comment by SamJokO** [comment]
Working Perfect! Thank you.
