### ISSUE TITLE
Logger weird action in Linux 

### ISSUE THREAD

**Issue by hippowar** [exilon/QuickLogger#26]
Hi, exilon.

I tested in CentOS with Quick.Logger.
Perfect working with "Debug" binary.
But, "Release" is raise exception.
I tried GlobalLogFileProvider fork and without fork.
it's makes trouble.
from SystemInfo.UserName. 

if iiUserName in IncludedInfo then WriteToStream(Format('Username    : %s',[Trim(SystemInfo.UserName)])); <-- this is raise exception. (Access violation...)

i'll try temporary way like this. (in Quick.SysInfo)

fUserName := String.Copy(GetLoggedUserName);
fUserName := Copy(fUserName, 1, Length(Trim(fUserName)));

just one line add.
than, working well. (Wrinteln is working too...  :< )
i don't know why...
something in weird working pointer with "Release" build mode, i think.

thank you.

**Comment by exilon** [comment]
Thanks SamJokO i will check it.

**Comment by exilon** [comment]
Hi SamJokO,
I've only tested with Ubuntu and couldn't reproduce your problem, but i've could reproduce some similar ones with GetComputerName. Seems like a strange behavior, with some posix functions. I've made a little "fix" to solve it. Please check it out now.

**Comment by SamJokO** [comment]
Hi exilon.

I've tested in CentOS 7.2.1511. it's not working. 
i tried like this in TSystemInfo.GetInfo
```
fUserName := GetLoggedUserName;
Writeln(fUserName);
```
that's working.
i think, maybe compiler problem.. i don't know.

**Comment by exilon** [comment]
Have you posibilities to test your application in ubuntu?

**Comment by exilon** [comment]
Delphi has official support for (see Embarcadero features matrix): Ubuntu 18.04 LTS, Ubuntu 16.04 LTS,
Ubuntu 14.04 LTS, and RedHat Enterprise Linux (version 7)

**Comment by SamJokO** [comment]
Hi, it's too late. sorry.
I test in Ubuntu 18.04 LTS. it is crush too.

> Delphi has official support for (see Embarcadero features matrix): Ubuntu 18.04 LTS, Ubuntu 16.04 LTS,
> Ubuntu 14.04 LTS, and RedHat Enterprise Linux (version 7)
