### ISSUE TITLE
Log files not being written when called from a Windows Service.

### ISSUE THREAD

**Issue by epachsoft** [exilon/QuickLogger#27]
Hi there,
I'm using Delphi Rio 10.3.2.  I'm moving all my Windows Services to use QuickLogger but I'm having problems with it.

When the logger is executed from a normal application (console or GUI) log files are written properly, Rotated Logs directory is created, etc, etc.  But when executed as a service log files are not being written.  I tried playing with permissions with no avail, is there something I might be missing? or some consideration I should have?  I use Windows 2016 for service testing and Windows 10 when testing it as a console.

Thank you in advance.

**Comment by exilon** [comment]
If you are running your service with Quick.AppService, stop it and run from exe location directly as administrator. If this action works could be an UAC issue.
Could you send me your Logger settings?

**Comment by epachsoft** [comment]
Hello,
I temporary changed the windows service account to use a domain admin user and it is now creating and updating the file, but the Rotated logs are not being created.  The start of a new day it overwrites the file.  Here it is the File appender, maybe you can pick something up.  My expectation is to have a daily rollup but also to create new files if their size goes over the 300MBs.  

Thank you in advance for all your help.

>  // lets create directory

     if not TDirectory.Exists('.\Logs') then
      TDirectory.CreateDirectory('.\Logs');


    //configure File log provider
    Logger.Providers.Add(GlobalLogFileProvider);
    with GlobalLogFileProvider do
    begin
      FileName := '.\Logs\'+lLogFileName;
      DailyRotate := True;
      LogLevel := LOG_VERBOSE;
      TimePrecission := True;
      MaxFileSizeInMB := 300;
      RotatedFilesPath := '.\RotatedLogs';
      CompressRotatedFiles := False;
      Enabled := True;
      ShowEventType := True;
      IncludedInfo := [iiAppName, iiHost, iiUserName, iiEnvironment, iiPlatform, iiOSVersion, iiExceptionInfo, iiExceptionStackTrace, iiThreadId, iiProcessId];
    end;

>

**Comment by exilon** [comment]
Could you check if overwrited log file has same datetime than previous one or has a new datetime?

**Comment by epachsoft** [comment]
The file date and time changes to the latest date and time modified date. (at least it gets updated the moment you open the file on any text editor, then the datetime is refreshed in the windows explorer which is normal).

The header of the log file is written again ... but with a new start datetime.  The old contents of the file are lost.
----------------------------------------------------------------------
Application : GX.Cerberus 3.0
PID         : 5176
Path        : E:\Cerberus\3.0.0.0\
CPU cores   : 3
OS version  : Windows Server 2016 (Version 10.0, Build 14393, 64-bit Edition)
Host        : XXXX
Username    : adminuser
Started     : 12-12-2019 00:00:37.845 
----------------------------------------------------------------------

**Comment by exilon** [comment]
Daily rotate logs bug was fixed. Please check if your service rotates logs now. Thanks.

**Comment by epachsoft** [comment]
It seems to be working. Thank you very much.
