### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by JohannKatzendorn** [exilon/QuickLogger#29]
Hi,
I try to use the FileProvider Quicklogger on a windows machine. But i get after some minutes an error and my application crached / hanged.

I use the logging from many different Threads. I have a mutex around the Log() function.
It seems that the problem come after large logs. Maybe a problem in the queue handle? Multiple access? 

Have you an idea what i can do?

My Initialization:

  Logger.Providers.Add(GlobalLogFileProvider);
  // Configure provider options
  with GlobalLogFileProvider do
  begin
    filename := '.\Logs_Planning\Logger.log';
    DailyRotate := True;
    MaxFileSizeInMB := 200;
    LogLevel := [etHeader, etError, etInfo, etSuccess, etWarning];
    TimePrecission := false;
    MaxFailsToRestart := 2;
    MaxFailsToStop := 10;
    CustomMsgOutput := false;
    UsesQueue := True;
    Enabled := True;
  end;

My use:

procedure LogQuickMessage(Msg: String; msgType: TCodeSiteTypes = cslDefault; filename: String = '');
begin
  try
    FMutex.Acquire;
    Log(Msg, CastCStoETEnum(msgType));
  finally
    FMutex.Release;
  end;
end;

Best Regards
Johann

**Comment by exilon** [comment]
You don't need mutex because Quick.Logger is threadsafe. QuickLogger is queue based. Every log entry is sendend to an internal queue and a background process reads from that queue and writes to file. We have big log processes running in production environments without any crash. Please, remove fmutex from your LogQuickMessage:

```
procedure LogQuickMessage(Msg: String; msgType: TCodeSiteTypes = cslDefault; filename: String = '');
begin
  Log(Msg, CastCStoETEnum(msgType));
end;
```

**Comment by JohannKatzendorn** [comment]
Without mutex still the same problem. The Event log  says that the file is used by another process, But only the Quicklogger use the file.

Here my Windows EventLog.

Die Beschreibung für die Ereignis-ID "0" aus der Quelle "ESD_AutoStorePlanningService" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.

Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.

Die folgenden Informationen wurden mit dem Ereignis gespeichert: 

Service fehlgeschlagen bei start:Datei C:\Users\johann.katzendorn\Documents\HG\autostore-anwendungen\PlanningService\Win32\Debug\Logs_Planning\Logger.log kann nicht geöffnet werden. Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird

**Comment by exilon** [comment]
Which delphi/fpc version are you using?
Could you reproduce this issue with QuickLogger sample program?

**Comment by exilon** [comment]
This issue was closed because it has been inactive for a long time.
