### ISSUE TITLE
Suggestion: Line format

### ISSUE THREAD

**Issue by epachsoft** [exilon/QuickLogger#30]
Hi,

The suggestion:
Allow to specify a line format.  For example, if you set something like:

LogProvider.LineFormat := '%{DATE} %{TIME} %{LEVEL} - ThreadId: %{THREADID} - PId: %{PID} - %{MSG}';

Where %{} is a way to access pre-defined built in output primitives from quicklogger.  It will allow to customize the output to match other loggers if there is a need to standarized on a log format.  Also if there are Logstash grok filters its easier to just follow an existing filter than customize the format to a specific one.

This can be later on improved by allowing to enter other pre-defined fixed values before the logger is initialize.  For example:

QuickLoggerOutPutDictionary["Module"] := 'Finance';
QuickLoggerOutPutDictionary["KEY"]:= 'FIN';

So you can extend the line format to support things like:

LineFormat := '%{DATE} %{TIME} %{LEVEL} %{MODULE} %{KEY} - ThreadId: %{THREADID} - PId: %{PID} - %{MSG}';

Or you can simply implement the dictionary first and add by default the existing output primitives.  

This is just a suggestion.  I will probably ended up patching quicklogger LogItemToLine to achieve this behaviour but it will be great if something like this comes built into QuickLogger.

Thank you in advance for your great work.

**Comment by exilon** [comment]
Finally, i've added possibility to customize output for each provider and use internal variables and custom tags. Get QuickLib & QuickLogger last changes and see updated documentation.
