### ISSUE TITLE
How to capture application exceptions?

### ISSUE THREAD

**Issue by AlekseyRykov2018** [exilon/QuickLogger#32]
Hello! Can you explain in more details how to capture application exceptions (ex. Access Violation)? 
I added Quick.Logger.ExceptionHook, Quick.Logger.RuntimeErrorHook, Quick.Logger.UnhandledExceptionHook to uses clause, 
but application exceptions don't writed to log file (use only GlobalLogFileProvider).

**Comment by exilon** [comment]
Add Quick.Logger.ExceptionHook to log everytime a except block reached, or Quick.Logger.UnhandledExceptionHook for exceptions that occurs outside a try..except block.
Check LogLevel in your provider. Please try assigning LOG_ALL to log each type of errors.
Sample project code has a forced exception to see how ExceptionHook works.
