### ISSUE TITLE
Adding Custom Fields

### ISSUE THREAD

**Issue by ZebedeeTR** [exilon/QuickLogger#33]
Hello. 
I'm using QuickLogger and GrayLog.
I can receive Error and Success messages.

I want to add a few custom fields.
Example: **version**, **module**, **customer**... etc.

I can send a message myself like this;
`Logger.Succ('Currency Downloaded Successfuly.');`
and I want to add these fields in auto-captured error messages...

Is there any way I can do this?

My config is below.
```  Logger.Providers.Add(GlobalLogGrayLogProvider);
  with GlobalLogGrayLogProvider do
  begin
    URL := 'http://192.168.1.248:12202';
    LogLevel := LOG_DEBUG;
    MaxFailsToRestart := 5;
    MaxFailsToStop := 0;
    {$IFDEF DEBUG}
      Environment := 'DEBUG';
    {$ELSE}
      Environment := 'RELEASE';
    {$ENDIF}
    PlatformInfo := 'WinService';
    IncludedInfo := [iiAppName, iiHost, iiUserName, iiEnvironment, iiPlatform, iiOSVersion, iiExceptionInfo, iiExceptionStackTrace, iiThreadId, iiProcessId];
    ShortMessageAsEventType := False;
    Enabled := TRUE;
  end;
```

    Logger.Succ('Currency Downloaded Successfuly.');

**Comment by ZebedeeTR** [comment]
According to the information written in the GELF document, we can define a Custom Field with an underscore. How can I use this information in QuickLogger?
http://docs.graylog.org/en/latest/pages/gelf.html

**Comment by ZebedeeTR** [comment]
I moved  **LogToGELF** function to **protected** in GrayLog unit and made it virtual.
I created my own provider by inheriting TLogGrayLogProvider and override LogToGELF function for gathering more information on my own interest.

It Works fine.

**Comment by exilon** [comment]
Finally, i've added possibility to customize output for each provider and use internal variables and custom tags.
