### ISSUE TITLE
Suggestion: WriteToStream -> Protected.

### ISSUE THREAD

**Issue by epachsoft** [exilon/QuickLogger#34]
Hi there,
I was writing a new provider based on the Provider.Files.  Provider.Files has a lot of valuable methods and data that can be reused but I noticed that a key part of it was made private so I cant use it.

WriteToStream.

Could it be made protected? (I did on my version but it will be nice if it is part of the core logger so my provider doesn't hurt what is there).

Thank you.

**Comment by exilon** [comment]
Yes, i will do.

**Comment by exilon** [comment]
I did. Some methods are protected & virtual now.
