### ISSUE TITLE
[Suggestion] - Log provider for Sentry.io

### ISSUE THREAD

**Issue by edwinyzh** [exilon/QuickLogger#35]
And here is some info to get started:

https://medium.com/@Zawuza/collect-exceptions-from-delphi-applications-using-sentry-eb90e689f76b

**Comment by exilon** [comment]
Thanks for your suggestion. I've added a new Sentry provider. Please, check it and give me your feedback.

**Comment by edwinyzh** [comment]
Thank you @exilon !

Tried, I'm using XE4, and got the "[dcc32 Error] Quick.FaultControl.pas(109): E2010 Incompatible types: 'System.TArray<System.Integer>' and 'Set'" error.
Will find another time to try it again.

**Comment by exilon** [comment]
Solved. Please get changes from QuickLib & QuickLogger repositories.

**Comment by edwinyzh** [comment]
Great job! I confirm sentry.io can receive the logs (with a little issue, see the screenshot below), the error shown in the sentry.io console is:

> There was 1 error encountered while processing this event:
> timestamp: Invalid timestamp (in future) 

![2020-04-29_15h54_31](https://user-images.githubusercontent.com/541197/80573015-d03e5d00-8a31-11ea-944f-b5baceaadc69.png)
