### ISSUE TITLE
Cannot compile samples/Firemonkey/MultiLog with Delphi Sydney (10.4.0) for iOS

### ISSUE THREAD

**Issue by zacares** [exilon/QuickLogger#38]
After open the sample project MultiLog, add project search path for QuickLib and QuickLogger, Press F9 and got error in Quick.Common.pas line 963.

> [DCC Error] Quick.Commons.pas(963): E2003 Undeclared identifier: 'TNSHost'

There is no problem with Delphi Rio (10.3.3) with the same steps.

Any idea?

Thanks.

**Comment by exilon** [comment]
Solved. You need to get Quick.Lib and Quick.Logger lastest versions.
