### ISSUE TITLE
Missing from GetIt Package Manager in 10.4

### ISSUE THREAD

**Issue by rhazell-numze** [exilon/QuickLogger#44]
It appears that QuickLogger & QuickLib are both missing from the GetIt Package Manager in both 10.4 & 10.4.1

Will it be returning anytime soon?

**Comment by exilon** [comment]
I'm waiting for Embarcadero to include both libraries.

**Comment by exilon** [comment]
QuickLib & Quicklogger are available again from Getit Package Manager in 10.4.x
