### ISSUE TITLE
GetIt package problem

### ISSUE THREAD

**Issue by Spelt** [exilon/QuickLogger#45]
Hi

I installed QuickLogger to Sydney 10.4.1/windows 32 and it looked ok but it looks like there is a problem.

I tried my first project with the logger but it does not seem to find some files.

I did:

uses
    Quick.Logger,
    Quick.Logger.Provider.Files,
    Quick.Logger.Provider.Console;

and it could not find the files:

  Quick.Logger.Intf,
  Quick.JSON.Utils,
  Quick.Json.Serializer,

etc.

It seems that they are not included in the package manager but a lot of c# code is there?

Sincerely, Edward

**Comment by exilon** [comment]
You need QuickLib. Two libraries should be installed when you install QuickLogger from GetIt.

**Comment by Spelt** [comment]
Thanks for your reply.
[QuickLogger-1.44.zip](https://github.com/exilon/QuickLogger/files/5683020/QuickLogger-1.44.zip)

The problem is that the Quicklogger package from GetIt did not install Quick lib. 

I attached a zip file with the contents what got installed.

**Comment by exilon** [comment]
It's a GetIt problem. I've reported to Embarcadero, but you could install QuickLib directly from GetIt if you want Quicklogger works meanwhile Embarcadero solves it.

**Comment by Spelt** [comment]
Ok thanks for the help!

**Comment by exilon** [comment]
Finally, dependency was solved by GetIt.
