### ISSUE TITLE
EinvalidPointer exception with GlobalLogEventLogProvider on close

### ISSUE THREAD

**Issue by Nico207** [exilon/QuickLogger#47]
Hi,

I've done a simple form with just QuickLogger inside

```delphi

uses
[...]
    ,Quick.Logger,Quick.Logger.Provider.EventLog;

[...]

procedure TForm2.FormCreate(Sender: TObject);
begin
    Logger.Providers.Add(GlobalLogEventLogProvider);
    GlobalLogEventLogProvider.Enabled:=True;
    Log('Hello world', etInfo);
end;

```
All works perfectly, but when I close this windows, I've got an exception (EinvalidPointer) with the message "Opération de pointeur incorrecte" (Invalid Pointer Operation)

It works without problems when I use GlobalLogFileProvider.

**Comment by exilon** [comment]
Thanks, it's solved now!
