### ISSUE TITLE
Each log entry can be duplicated

### ISSUE THREAD

**Issue by FBUtveckling** [exilon/QuickLogger#48]
I am using the library for a simple record of the execution time of some consecutive processes.

Using the file provider, the first time the method sequence is executed, the log record works correctly, but if the sequence is executed again, after the first sequence, the log record duplicates each entry.

I imagine it could be a registry buffer bug?

Summarizing

Using Log('Start: 16:53:03.239', etInfo) for each line.
First round: 
Processing...
Start: 16:53:03.239
End: 00:00:00.0000

Second round:
Processing...
Processing...
Start: 16:53:04.239
Start: 16:53:04.239
End: 00:00:00.0000
End: 00:00:00.0000

**Comment by exilon** [comment]
Could you explain how you're using Quick.Logger in your project? File provider is running for long time in production environments without problems. Quick.Logger has a global buffer and retrieves each entry only one time and deletes it, it's not possible to retrieve same entry two times.

**Comment by FBUtveckling** [comment]
Hi,

I use QuickLogger in a unit that is composed of an Object type component that generates a dialog that shows the operation progress of a particular routine.

I initialize QuickLogger in the Create method of the component and define the FileProvider as the destination of the messages.

At the beginning of the method that executes the routine, it sent two start messages indicating the start and name of the process; the routine consists of the consecutive execution of another routine and measures the duration of each execution and sends the information to the Log (...).

This routine is passed as a parameter to the dialog box that shows the progress, this dialog box is modal, so the routine must be passed as a parameter and so it can be executed from the code of the dialog box.

The first time everything works as expected, one line for each Log (...) but, if the routine is executed again, without modifying anything in the QuickLogger, the result is that each Log (...) message is duplicated.

**Comment by FBUtveckling** [comment]
I recognize that the library is extremely useful and easy to implement.

Now I understand what the problem would be but it would definitely be a BUG in the library.

When the following two configurations are included, every time the same process is executed, the library creates a link with a log file, the same name is used with the same location path, but the library is not capable of recognize that it is the same file and creates a multi link with the file and that is why the same lines are written, repeatedly, as many times as the routine that sends the log is executed.

```
procedure TForm1.Button1Click(Sender: TObject);
begin
  Logger.Providers.Add(GlobalLogFileProvider);
  with GlobalLogFileProvider do
 	begin
    	FileName := 'C:\Temp\Logger.log';
        DailyRotate := True;
        MaxFileSizeInMB := 20;
        LogLevel := LOG_ALL;
    	Enabled := True;
  end;
  Log(StringOfChar('.', 30), etInfo);
  Log('Test entry', etInfo);
  Log(StringOfChar('.', 30), etInfo);
end;
```
At the first click 3 lines are written, the second time is clicked, 6 lines will be written, two for each line sent, the third time each line sent will be written n times equal to the number of times clicked.

The library should be able to identify that the same file is being referenced and therefore not send the same information multiple times, if this happens in a simple application I imagine that it could happen in a complex application where it is impossible to keep an absolute track of everything the code that has been written.

**Comment by exilon** [comment]
Sorry, but if you're adding same provider every time you click button i treat as a misconfiguration, not a bug. I think isn't a library responsability to check if you are duplicating providers. Providers are added as interfaces and library doesn't need to know about concrete provider configuration. This is the magic of QuickLogger that allows it to be modulable and upgradable with custom providers. Please, see firemonkey samples to check how providers must be configured.

Many people are using this library in big production applications since 2018 with no problems.
