### ISSUE TITLE
Loading a Settingsfile.json for GlobalLogFileProvider generates duplicatet Header in Log file

### ISSUE THREAD

**Issue by pmeder** [exilon/QuickLogger#50]
Hi,

I tried to save and load json configuration file for FileLogProvider. When I do so, my Logfile gets 2 Headers everytime. That leads me to the opinion I somehow double inititate the logger, but that was not the case.
Seams to be a bug with tlogger.Provider.fromJson

Best regards

**Comment by exilon** [comment]
Could you send me a example code?

**Comment by exilon** [comment]
Close innactive
