### ISSUE TITLE
Error 401 when trying to create a database in InfluxDB

### ISSUE THREAD

**Issue by DavidIzadaR** [exilon/QuickLogger#51]
According to a similar issue reported for Grafana, sometimes it is necessary to include an Authorization token in the HTTP header during the POST for creating the database.
In my case, I was the owner of the organization and I created two tokens, one for common access (reading and writing to an existing database), and another for creating a database on-the-fly.
I couldn't create the database with my username and password.
There is a Post method for fHTTPClient ready to receive JSON pairs, but there is no token in the provider class.

**Comment by exilon** [comment]
Are you talking about influxdb1.8  or 2.0?

**Comment by exilon** [comment]
This issue was closed because it has been inactive for a long time.
