### ISSUE TITLE
AutoFlush Bug

### ISSUE THREAD

**Issue by piotrx** [exilon/QuickLogger#66]
Hi,

In Quick.Logger.Provider.Files.pas line 257

is 

```
//needs to flush if autoflush??
if not fAutoFlush then fLogWriter.Flush;
```

should be

```
//needs to flush if autoflush??
if fAutoFlush then fLogWriter.Flush;
```

**Comment by exilon** [comment]
This is not a bug. Autoflush means system controls when to write buffer lines to file, avoiding continuos file writes (recomended), but if autoflush is disabled, every log line will be written to file (this is recomended only when is critical to get every log line on application crashes).

**Comment by piotrx** [comment]
Ok ... thx for the info how it works ... I close issue.
