### ISSUE TITLE
[Feature Request]: A TMemo provider

### ISSUE THREAD

**Issue by gcarreno** [exilon/QuickLogger#67]
Hey @exilon ,

Would it be feasible to add a `TMemo` provider?

Thanks in advance!!

Cheers,
Gus

**Comment by exilon** [comment]
You can do with EventsProvider:

```
//define log provider
GlobalLogEventsProvider.LogLevel := LOG_ALL;
  GlobalLogEventsProvider.OnAny :=  OnNewLog;
  GlobalLogEventsProvider.Enabled := True;
  Logger.Providers.Add(GlobalLogEventsProvider);

//method in form where your TMemo exists
procedure TfrmMain.OnNewLog(LogItem: TLogItem);
begin
  TThread.Synchronize(nil,
  procedure
  begin
    meLog.Lines.Add(Format('%s [%s] %s (TreadId: %d)',[DateTimeToStr(LogItem.EventDate),LogItem.EventTypeName,LogItem.Msg,LogItem.ThreadId]));
  end
  );
end;
```

**Comment by gcarreno** [comment]
Hey @exilon,

I somehow was under the impression that you'd had it covered, but was a bit lazy to rummage through the code to dig it out!!

Thank you very much for the solve and the quick response, really appreciate it :smile: 

Cheers,
Gus

**Comment by luebbe** [comment]
@gcarreno be careful however that the memo will become terribly slow when it is running "full".

**Comment by gcarreno** [comment]
Hey Lübbe(@luebbe),

Yeah, I'm thinking about clearing or culling the `TMemo` periodically since it's just a quick visual aid.
The real logging, for historical and completeness purposes will be the file.

But, nonetheless, thanks for the warning :smiley: 

Cheer,
Gus
