### ISSUE TITLE
Logger raise exception in FMX (Android 64, MacOS)

### ISSUE THREAD

**Issue by SamJokO** [exilon/QuickLogger#68]
Hello,

latest version of QuickLogger raise exception in FMX (Android 64 bit, MacOS)
exception is "Range Check Error"
- cause
TLogger.EnQueueItem(cLogItem: TLogItem)
begin
...
cLogItem.ThreadId := TThread.CurrentThread.ThreadId; <---- Here. (line no : 1409)
...
end;

because,
ThreadId defined in System.pas
{$IF Defined(MSWINDOWS)}
  TThreadID = LongWord;
{$ENDIF}
{$IFDEF POSIX}
  TThreadID = NativeUInt;
{$ENDIF}

like this.
but, in TLogItem.ThreadId is DWORD. invalid type. UInt32 and UInt64.

**Comment by exilon** [comment]
Solved, thanks!
