### ISSUE TITLE
Exception in QuickLogger.Provider.Memory -> WriteLog if MaxSize > 0

### ISSUE THREAD

**Issue by pjrobin** [exilon/QuickLogger#69]
Minor problem:
in  procedure TLogMemoryProvider.WriteLog(cLogItem : TLogItem); you have
      repeat fMemLog.Delete(0) until fMemLog.Count < fMaxSize;
this produce an exception when writing the first Log message. 
Should be replaced with
      while fMemLog.Count >= fMaxSize do fMemLog.Delete(0);

**Comment by exilon** [comment]
Thanks, now it's fixed.
