### ISSUE TITLE
What versions of Delphi this library supports?

### ISSUE THREAD

**Issue by V0d01ey** [exilon/QuickLogger#7]
When trying to use QuickLogger under Delphi XE6 following code line gives an error 
https://github.com/exilon/QuickLogger/blob/1daa0b7d3e035892ba55c2791dd185cd4cee7e57/Quick.Logger.pas#L263
> [dcc32 Error] Quick.Logger.pas(263): E2003 Undeclared identifier: 'TJSONObject'

Can you add to documentation which versions are supported?

**Comment by exilon** [comment]
Thanks for your pull request. Versions supported are XE8 and up.
