### ISSUE TITLE
Setting GlobalLogFileProvider.FileName after enabled causes AV error later

### ISSUE THREAD

**Issue by nbuyer** [exilon/QuickLogger#70]
Hi,
I tried to use this logger the very first time and encountered some minor issues.
It is very easy to avoid but I just want to report what happened. Thank you.

Delphi 11.1
FMX.MultiLogger project

procedure TfrmMain.FormCreate(Sender: TObject);
begin
  GlobalLogFileProvider.LogLevel := LOG_ALL;
  GlobalLogFileProvider.Enabled := True;
  // 1. BTW, can not do this: GlobalLogFileProvider.FormatSettings.ShortDateFormat := 'yyyy-mm-dd hh:nn:ss';
  // 2. Setting GlobalLogFileProvider.FileName after enabled causes AV error later
  GlobalLogFileProvider.FileName := '.\abc.log';
  GlobalLogFileProvider.IncludedInfo := GlobalLogFileProvider.IncludedInfo + [iiThreadId];
...

**Comment by nbuyer** [comment]
> // 1. BTW, can not do this: GlobalLogFileProvider.FormatSettings.ShortDateFormat := 'yyyy-mm-dd hh:nn:ss'; Do you mean date format output in your file not corresponds to your selected format?

No, just a compiler error: [dcc32 Error]  E2064 Left side cannot be assigned to

**Comment by exilon** [comment]
> // 2. Setting GlobalLogFileProvider.FileName after enabled causes AV error later

I've tried and i can change filename after enabled and new log entries was written to new file. Can you provide more info?

**Comment by nbuyer** [comment]
Thanks!
New a VCL form and put a button1 on it.

procedure TForm11.Button1Click(Sender: TObject);
begin
  GlobalLogFileProvider.LogLevel := LOG_ALL;
  GlobalLogFileProvider.IncludedInfo := GlobalLogFileProvider.IncludedInfo + [iiThreadId];
  GlobalLogFileProvider.FileName := '.\abc.log';
  GlobalLogFileProvider.Enabled := True;
  GlobalLogFileProvider.FileName := '.\def.log'; // Remove this line to stop AV
  Logger.Providers.Add(GlobalLogFileProvider);
end;

Click the button1  and will throw this exception:

---------------------------
Debugger Exception Notification
---------------------------
Project Project11.exe raised exception class $C0000005 with message 'access violation at 0x01066e1e: read of address 0x00700041'.
---------------------------
Break   Continue   Copy   Help   
---------------------------

Quick.Threads.pas line 940

function TThreadedQueueList<T>.PopItem(var AQueueSize: Integer; var AItem: T): TWaitResult;
begin
  AItem := Default(T);
  fQueueLock.Enter;   // <-- Exception break on this line

**Comment by exilon** [comment]
What delphi version are you using?

**Comment by exilon** [comment]
Please, change line 372 in Quick.Logger.Provider.Files:

`if IsEnabled then Restart;`

with:

`if IsEnabled then Init`

**Comment by nbuyer** [comment]
> Please, change line 372 in Quick.Logger.Provider.Files:
> 
> `if IsEnabled then Restart;`
> 
> with:
> 
> `if IsEnabled then Init`

Problem solved!
