### ISSUE TITLE
Incompatible types: 'array of TVarRec' and 'Procedure'

### ISSUE THREAD

**Issue by FIFernandes** [exilon/QuickLogger#72]
If I have  Quick.Threads in the interface/uses I get an compile error:  

 aTask := TTask.Create(
     procedure( )
      begin
     end );  <<<Incompatible types: 'array of TVarRec' and 'Procedure'
aTask.Start;

Delphi 10.3.3

**Comment by exilon** [comment]
TTask constructor needs 3 params:

`constructor TTask.Create(aParamArray : array of const; aOwnedParams : Boolean; aTaskProc : TTaskProc);`

You have missed two previous params.

```
aTask := TTask.Create([],False,
procedure( )
begin
end ); <<<Incompatible types: 'array of TVarRec' and 'Procedure'
aTask.Start;
```
