### ISSUE TITLE
Logger in a TThread.Execute does not output

### ISSUE THREAD

**Issue by FIFernandes** [exilon/QuickLogger#77]
I have a logger in a TThread.Execute in Delphi windows service. The logger does not output to a text file. It outputs in the TService just after it is installed.

In the used I have 
    Quick.Logger,
    Quick.Threads,
    Quick.Logger.Provider.Files,

 Logger.Succ( 'Worker started ' + TimeToStr( Now ) );

Thanks

**Comment by exilon** [comment]
You need to add provider to logger before use Logger.Succ

```
Logger.Providers.Add(GlobalLogFileProvider);
GlobalLogFileProvider .Enable := True;
```
