### ISSUE TITLE
Encrypt logfile?

### ISSUE THREAD

**Issue by SofttouchCode** [exilon/QuickLogger#85]
is there a way to encrypt the output before its written to a file? Sometimes, sensitive information need to be logged, not for the eyes of everyone.

**Comment by jfudickar** [comment]
Do you want to encrypt one message or the whole file?

**Comment by jfudickar** [comment]
I've looked into it, i think it's not so simple to reach this.
Maybe someone else has a good idea and want's to make a fork for that.

**Comment by SofttouchCode** [comment]
Thats ok. I thought it might be easy. Thanks for the info.

**Comment by exilon** [comment]
You could  create a provider based on FileProvider but with encryption capabilities to write every line encrypted before write to disk, then your entire file will be encrypted.
