### ISSUE TITLE
Delphi XE compatibility

### ISSUE THREAD

**Issue by SirRigorMortis** [exilon/QuickLogger#97]
Delphi XE compiler requires $IFEND for $IF derective instead of $ENDIF

> [DCC Error] QuickLib.inc(73): E2029 $IFEND expected but $ENDIF found

**Comment by exilon** [comment]
As you can see in readme.md, libraries are compatibility with Delphi(Delphi XE6 - Delphi 11 Alexandria)/Freepascal(trunk)/.NET (Windows/Linux/Android/MACOSX/IOS)
